/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsCategoriesRouteImport } from './routes/settings-categories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'
import { Route as LoansIdRouteImport } from './routes/loans.$id'
import { Route as BudgetIdRouteImport } from './routes/budget.$id'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings-categories',
  path: '/settings-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LoansRoute,
} as any)
const BudgetIdRoute = BudgetIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BudgetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRouteWithChildren
  '/imports': typeof ImportsRoute
  '/loans': typeof LoansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/settings-categories': typeof SettingsCategoriesRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/budget/$id': typeof BudgetIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRouteWithChildren
  '/imports': typeof ImportsRoute
  '/loans': typeof LoansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/settings-categories': typeof SettingsCategoriesRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/budget/$id': typeof BudgetIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRouteWithChildren
  '/imports': typeof ImportsRoute
  '/loans': typeof LoansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/settings-categories': typeof SettingsCategoriesRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/budget/$id': typeof BudgetIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/assets'
    | '/budget'
    | '/imports'
    | '/loans'
    | '/settings'
    | '/settings-categories'
    | '/subscriptions'
    | '/budget/$id'
    | '/loans/$id'
    | '/subscriptions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/assets'
    | '/budget'
    | '/imports'
    | '/loans'
    | '/settings'
    | '/settings-categories'
    | '/subscriptions'
    | '/budget/$id'
    | '/loans/$id'
    | '/subscriptions/$id'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/assets'
    | '/budget'
    | '/imports'
    | '/loans'
    | '/settings'
    | '/settings-categories'
    | '/subscriptions'
    | '/budget/$id'
    | '/loans/$id'
    | '/subscriptions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AssetsRoute: typeof AssetsRoute
  BudgetRoute: typeof BudgetRouteWithChildren
  ImportsRoute: typeof ImportsRoute
  LoansRoute: typeof LoansRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-categories': {
      id: '/settings-categories'
      path: '/settings-categories'
      fullPath: '/settings-categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof LoansRoute
    }
    '/budget/$id': {
      id: '/budget/$id'
      path: '/$id'
      fullPath: '/budget/$id'
      preLoaderRoute: typeof BudgetIdRouteImport
      parentRoute: typeof BudgetRoute
    }
  }
}

interface BudgetRouteChildren {
  BudgetIdRoute: typeof BudgetIdRoute
}

const BudgetRouteChildren: BudgetRouteChildren = {
  BudgetIdRoute: BudgetIdRoute,
}

const BudgetRouteWithChildren =
  BudgetRoute._addFileChildren(BudgetRouteChildren)

interface LoansRouteChildren {
  LoansIdRoute: typeof LoansIdRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansIdRoute: LoansIdRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AssetsRoute: AssetsRoute,
  BudgetRoute: BudgetRouteWithChildren,
  ImportsRoute: ImportsRoute,
  LoansRoute: LoansRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
