/**
 * @purpose Static mock data for the ported Assets page's tRPC queries.
 * @role    Plain data module exporting one object keyed by dotted tRPC path; the verbatim-copied
 *          AssetsPage renders realistic Chinese demo balances near 2026-06-21.
 * @deps    Contract shapes from @flowm/shared/contracts (AssetSnapshotSummary / AssetItemSummary).
 * @gotcha  The mock tRPC registry strips query args, so every assets.snapshots variant resolves to
 *          ONE dataset — registered with the latest, non-archived snapshots only so the default
 *          grouped list + treemap stay clean. Totals: assets ¥4,100,000 · liabilities ¥1,200,000.
 */

import type { AssetItemSummary, AssetSnapshotSummary } from "@flowm/shared/contracts"

// ── Latest snapshots (one current reading per active account) ───────────────
// Sum of non-liability values = 4,100,000; liabilities = 1,200,000.
const snapshots: AssetSnapshotSummary[] = [
  // 现金 (cash / bank / wallet) — 384,500
  {
    id: "as-cash",
    assetItemId: "ai-cash",
    accountName: "现金钱包",
    assetType: "cash",
    snapshotAt: "2026-06-18",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "8500",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  {
    id: "as-cmb",
    assetItemId: "ai-cmb",
    accountName: "招商银行储蓄",
    assetType: "bank",
    snapshotAt: "2026-06-20",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "320000",
    valueCurrency: "CNY",
    source: "manual",
    note: "工资卡",
    meta: null,
  },
  {
    id: "as-alipay",
    assetItemId: "ai-alipay",
    accountName: "支付宝余额宝",
    assetType: "wallet",
    snapshotAt: "2026-06-19",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "56000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  // 投资 (fund / stock) — 900,000
  {
    id: "as-fund",
    assetItemId: "ai-fund",
    accountName: "天弘基金组合",
    assetType: "fund",
    snapshotAt: "2026-06-15",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "520000",
    valueCurrency: "CNY",
    source: "manual",
    note: "定投",
    meta: null,
  },
  {
    id: "as-stock",
    assetItemId: "ai-stock",
    accountName: "招商证券股票",
    assetType: "stock",
    snapshotAt: "2026-06-17",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "380000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  // 不动产 (real_estate) — 2,400,000
  {
    id: "as-house",
    assetItemId: "ai-house",
    accountName: "自住房产估值",
    assetType: "real_estate",
    snapshotAt: "2026-06-01",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "2400000",
    valueCurrency: "CNY",
    source: "manual",
    note: "市中心两居",
    meta: null,
  },
  // 固定资产 (vehicle / fixed_asset) — 415,500
  {
    id: "as-car",
    assetItemId: "ai-car",
    accountName: "家用汽车",
    assetType: "vehicle",
    snapshotAt: "2026-06-10",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "180000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  {
    id: "as-gold",
    assetItemId: "ai-gold",
    accountName: "黄金积存",
    assetType: "fixed_asset",
    snapshotAt: "2026-06-12",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "235500",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  // 负债 (liability) — 1,200,000
  {
    id: "as-mortgage",
    assetItemId: "ai-mortgage",
    accountName: "房贷余额",
    assetType: "liability",
    snapshotAt: "2026-06-22",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "1050000",
    valueCurrency: "CNY",
    source: "manual",
    note: "招商银行 · 等额本息",
    meta: null,
  },
  {
    id: "as-credit",
    assetItemId: "ai-credit",
    accountName: "信用卡待还",
    assetType: "liability",
    snapshotAt: "2026-06-20",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "150000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
]

// ── Asset items (active + archived) ─────────────────────────────────────────
const items: AssetItemSummary[] = [
  {
    id: "ai-cash",
    name: "现金钱包",
    assetType: "cash",
    institution: null,
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: false,
    archivedAt: null,
    note: null,
  },
  {
    id: "ai-cmb",
    name: "招商银行储蓄",
    assetType: "bank",
    institution: "招商银行",
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: false,
    archivedAt: null,
    note: "工资卡",
  },
  {
    id: "ai-alipay",
    name: "支付宝余额宝",
    assetType: "wallet",
    institution: "蚂蚁集团",
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: false,
    archivedAt: null,
    note: null,
  },
  {
    id: "ai-fund",
    name: "天弘基金组合",
    assetType: "fund",
    institution: "天弘基金",
    defaultCurrency: "CNY",
    valuationMethod: "manual_market_value",
    archived: false,
    archivedAt: null,
    note: "定投",
  },
  {
    id: "ai-stock",
    name: "招商证券股票",
    assetType: "stock",
    institution: "招商证券",
    defaultCurrency: "CNY",
    valuationMethod: "manual_market_value",
    archived: false,
    archivedAt: null,
    note: null,
  },
  {
    id: "ai-house",
    name: "自住房产估值",
    assetType: "real_estate",
    institution: null,
    defaultCurrency: "CNY",
    valuationMethod: "manual_market_value",
    archived: false,
    archivedAt: null,
    note: "市中心两居",
  },
  {
    id: "ai-car",
    name: "家用汽车",
    assetType: "vehicle",
    institution: null,
    defaultCurrency: "CNY",
    valuationMethod: "manual_market_value",
    archived: false,
    archivedAt: null,
    note: null,
  },
  {
    id: "ai-gold",
    name: "黄金积存",
    assetType: "fixed_asset",
    institution: "工商银行",
    defaultCurrency: "CNY",
    valuationMethod: "manual_market_value",
    archived: false,
    archivedAt: null,
    note: null,
  },
  {
    id: "ai-mortgage",
    name: "房贷余额",
    assetType: "liability",
    institution: "招商银行",
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: false,
    archivedAt: null,
    note: "招商银行 · 等额本息",
  },
  {
    id: "ai-credit",
    name: "信用卡待还",
    assetType: "liability",
    institution: "招商银行",
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: false,
    archivedAt: null,
    note: null,
  },
  // Archived account (shown only in the 归档账户 drawer, not in totals).
  {
    id: "ai-old-bank",
    name: "工商银行旧卡",
    assetType: "bank",
    institution: "工商银行",
    defaultCurrency: "CNY",
    valuationMethod: "manual_balance",
    archived: true,
    archivedAt: "2026-03-14T00:00:00.000Z",
    note: null,
  },
]

// ── Sparklines (≥2 points per asset so the row change % renders) ────────────
const sparklines = [
  { assetItemId: "ai-cash", snapshotAt: "2026-05-18", valueNumber: "9200" },
  { assetItemId: "ai-cash", snapshotAt: "2026-06-18", valueNumber: "8500" },
  { assetItemId: "ai-cmb", snapshotAt: "2026-05-20", valueNumber: "298000" },
  { assetItemId: "ai-cmb", snapshotAt: "2026-06-20", valueNumber: "320000" },
  { assetItemId: "ai-alipay", snapshotAt: "2026-05-19", valueNumber: "53500" },
  { assetItemId: "ai-alipay", snapshotAt: "2026-06-19", valueNumber: "56000" },
  { assetItemId: "ai-fund", snapshotAt: "2026-05-15", valueNumber: "498000" },
  { assetItemId: "ai-fund", snapshotAt: "2026-06-15", valueNumber: "520000" },
  { assetItemId: "ai-stock", snapshotAt: "2026-05-17", valueNumber: "402000" },
  { assetItemId: "ai-stock", snapshotAt: "2026-06-17", valueNumber: "380000" },
  { assetItemId: "ai-house", snapshotAt: "2026-05-01", valueNumber: "2380000" },
  { assetItemId: "ai-house", snapshotAt: "2026-06-01", valueNumber: "2400000" },
  { assetItemId: "ai-car", snapshotAt: "2026-05-10", valueNumber: "186000" },
  { assetItemId: "ai-car", snapshotAt: "2026-06-10", valueNumber: "180000" },
  { assetItemId: "ai-gold", snapshotAt: "2026-05-12", valueNumber: "228000" },
  { assetItemId: "ai-gold", snapshotAt: "2026-06-12", valueNumber: "235500" },
  { assetItemId: "ai-mortgage", snapshotAt: "2026-05-22", valueNumber: "1054200" },
  { assetItemId: "ai-mortgage", snapshotAt: "2026-06-22", valueNumber: "1050000" },
  { assetItemId: "ai-credit", snapshotAt: "2026-05-20", valueNumber: "138000" },
  { assetItemId: "ai-credit", snapshotAt: "2026-06-20", valueNumber: "150000" },
]

// Latest snapshot per archived account (the drawer reads from this dataset too,
// but the mock registry collapses every assets.snapshots variant onto one key,
// so the archived row's balance is sourced from `latestSnapshotByAsset` which is
// built from these same active snapshots; the archived account simply shows none).
const netWorth = {
  netWorth: { number: "2900000", currency: "CNY" },
  assetValue: { number: "4100000", currency: "CNY" },
  liabilityValue: { number: "1200000", currency: "CNY" },
  missingFx: [],
}

const referenceCurrentRates = {
  base: "CNY",
  asOf: "2026-06-21",
  rates: {
    USD: "7.18",
    EUR: "7.82",
    HKD: "0.92",
    JPY: "0.046",
  },
}

export const assetsData: Record<string, unknown> = {
  "assets.snapshots": snapshots,
  "assets.items": items,
  "assets.sparklines": sparklines,
  "assets.netWorth": netWorth,
  "reference.currentRates": referenceCurrentRates,
}
