/**
 * @purpose Register static mock data for the ported Imports (流水) page's tRPC queries.
 * @role    Export keyed by dotted tRPC path so <MockProvider data={importsData}> populates the
 *          mock registry and the verbatim-copied ImportsPage renders realistic finance numbers.
 * @deps    Shapes mirror @flowm/api CashflowEventSummary + CategorySummary. Dates anchor near
 *          2026-06-21 so the default "本月" (this month) filter shows June 2026 activity.
 * @gotcha  Each event's categoryId must point at a reference.categories id so the category filter
 *          and right-side donut/breakdown group correctly.
 */

// ── Categories ──────────────────────────────────────────────────────────────
// Expense + income categories. ids match cashflow events' categoryId.
const categories = [
  {
    id: "cat-food",
    name: "餐饮",
    parentId: null,
    categoryKind: "expense",
    kind: "expense",
    color: "#e07b3a",
    icon: null,
    sortOrder: 1,
    displayOrder: 1,
    archived: false,
    archivedAt: null,
  },
  {
    id: "cat-trans",
    name: "交通",
    parentId: null,
    categoryKind: "expense",
    kind: "expense",
    color: "#4a8fc4",
    icon: null,
    sortOrder: 2,
    displayOrder: 2,
    archived: false,
    archivedAt: null,
  },
  {
    id: "cat-shop",
    name: "购物",
    parentId: null,
    categoryKind: "expense",
    kind: "expense",
    color: "#c46a9e",
    icon: null,
    sortOrder: 3,
    displayOrder: 3,
    archived: false,
    archivedAt: null,
  },
  {
    id: "cat-sub",
    name: "订阅",
    parentId: null,
    categoryKind: "expense",
    kind: "expense",
    color: "#7c6ac4",
    icon: null,
    sortOrder: 4,
    displayOrder: 4,
    archived: false,
    archivedAt: null,
  },
  {
    id: "cat-home",
    name: "居住",
    parentId: null,
    categoryKind: "expense",
    kind: "expense",
    color: "#5bac8e",
    icon: null,
    sortOrder: 5,
    displayOrder: 5,
    archived: false,
    archivedAt: null,
  },
  {
    id: "cat-income",
    name: "收入",
    parentId: null,
    categoryKind: "income",
    kind: "income",
    color: "#14794a",
    icon: null,
    sortOrder: 6,
    displayOrder: 6,
    archived: false,
    archivedAt: null,
  },
]

// ── Cashflow events ─────────────────────────────────────────────────────────
// June 2026 mix across 餐饮/交通/购物/订阅/居住 + 收入.
const cashflowEvents = [
  {
    id: "cf-1",
    statementLineId: "sl-1",
    eventDate: "2026-06-02",
    date: "2026-06-02",
    occurredAt: "2026-06-02T10:00:00Z",
    title: "盒马鲜生",
    counterparty: "盒马鲜生",
    description: "生鲜采购",
    userNote: null,
    amount: "286.40",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-food",
    categoryName: "餐饮",
    sourceKind: "import",
    sourceName: "招商银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-03T00:00:00Z",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [{ id: "tag-grocery", name: "生鲜" }],
    createdAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "cf-2",
    statementLineId: "sl-2",
    eventDate: "2026-06-04",
    date: "2026-06-04",
    occurredAt: "2026-06-04T09:00:00Z",
    title: "滴滴出行",
    counterparty: "滴滴出行",
    description: "通勤打车",
    userNote: null,
    amount: "62.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-trans",
    categoryName: "交通",
    sourceKind: "import",
    sourceName: "支付宝",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-05T00:00:00Z",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-04T09:00:00Z",
  },
  {
    id: "cf-3",
    statementLineId: "sl-3",
    eventDate: "2026-06-06",
    date: "2026-06-06",
    occurredAt: "2026-06-06T20:00:00Z",
    title: "京东商城",
    counterparty: "京东商城",
    description: "日用百货",
    userNote: null,
    amount: "458.90",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-shop",
    categoryName: "购物",
    sourceKind: "import",
    sourceName: "招商银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-07T00:00:00Z",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-06T20:00:00Z",
  },
  {
    id: "cf-4",
    statementLineId: "sl-4",
    eventDate: "2026-06-08",
    date: "2026-06-08",
    occurredAt: "2026-06-08T19:30:00Z",
    title: "海底捞",
    counterparty: "海底捞",
    description: "朋友聚餐",
    userNote: "周末聚会",
    amount: "512.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-food",
    categoryName: "餐饮",
    sourceKind: "import",
    sourceName: "微信",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-09T00:00:00Z",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [{ id: "tag-dining", name: "聚餐" }],
    createdAt: "2026-06-08T19:30:00Z",
  },
  {
    id: "cf-5",
    statementLineId: "sl-5",
    eventDate: "2026-06-10",
    date: "2026-06-10",
    occurredAt: "2026-06-10T00:00:00Z",
    title: "工资",
    counterparty: "公司发薪",
    description: "六月工资",
    userNote: null,
    amount: "32000.00",
    currency: "CNY",
    direction: "in",
    flowKind: "income",
    categoryId: "cat-income",
    categoryName: "收入",
    sourceKind: "import",
    sourceName: "招商银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-10T00:00:00Z",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [{ id: "tag-salary", name: "工资" }],
    createdAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "cf-6",
    statementLineId: "sl-6",
    eventDate: "2026-06-11",
    date: "2026-06-11",
    occurredAt: "2026-06-11T08:30:00Z",
    title: "星巴克",
    counterparty: "星巴克",
    description: "咖啡",
    userNote: null,
    amount: "39.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-food",
    categoryName: "餐饮",
    sourceKind: "import",
    sourceName: "支付宝",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-12T00:00:00Z",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-11T08:30:00Z",
  },
  {
    id: "cf-7",
    statementLineId: "sl-7",
    eventDate: "2026-06-13",
    date: "2026-06-13",
    occurredAt: "2026-06-13T15:00:00Z",
    title: "优衣库",
    counterparty: "优衣库",
    description: "夏装",
    userNote: null,
    amount: "699.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-shop",
    categoryName: "购物",
    sourceKind: "import",
    sourceName: "微信",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-14T00:00:00Z",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-13T15:00:00Z",
  },
  {
    id: "cf-8",
    statementLineId: "sl-8",
    eventDate: "2026-06-15",
    date: "2026-06-15",
    occurredAt: "2026-06-15T09:00:00Z",
    title: "网易云音乐",
    counterparty: "网易云音乐",
    description: "黑胶会员",
    userNote: null,
    amount: "15.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-sub",
    categoryName: "订阅",
    sourceKind: "import",
    sourceName: "支付宝",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-16T00:00:00Z",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [{ id: "tag-music", name: "音乐" }],
    createdAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "cf-9",
    statementLineId: "sl-9",
    eventDate: "2026-06-16",
    date: "2026-06-16",
    occurredAt: "2026-06-16T00:00:00Z",
    title: "物业费",
    counterparty: "万科物业",
    description: "六月物业费",
    userNote: null,
    amount: "480.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-home",
    categoryName: "居住",
    sourceKind: "import",
    sourceName: "建设银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-16T00:00:00Z",
    source: "建设银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-16T00:00:00Z",
  },
  {
    id: "cf-10",
    statementLineId: "sl-10",
    eventDate: "2026-06-17",
    date: "2026-06-17",
    occurredAt: "2026-06-17T12:00:00Z",
    title: "美团外卖",
    counterparty: "美团外卖",
    description: "工作日午餐",
    userNote: null,
    amount: "44.50",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-food",
    categoryName: "餐饮",
    sourceKind: "import",
    sourceName: "微信",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-18T00:00:00Z",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-17T12:00:00Z",
  },
  {
    id: "cf-11",
    statementLineId: "sl-11",
    eventDate: "2026-06-19",
    date: "2026-06-19",
    occurredAt: "2026-06-19T00:00:00Z",
    title: "理财收益",
    counterparty: "招商银行",
    description: "货币基金收益",
    userNote: null,
    amount: "186.20",
    currency: "CNY",
    direction: "in",
    flowKind: "income",
    categoryId: "cat-income",
    categoryName: "收入",
    sourceKind: "import",
    sourceName: "招商银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-19T00:00:00Z",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-19T00:00:00Z",
  },
  {
    id: "cf-12",
    statementLineId: "sl-12",
    eventDate: "2026-06-20",
    date: "2026-06-20",
    occurredAt: "2026-06-20T17:00:00Z",
    title: "永辉超市",
    counterparty: "永辉超市",
    description: "周末采购",
    userNote: null,
    amount: "312.80",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryId: "cat-food",
    categoryName: "餐饮",
    sourceKind: "import",
    sourceName: "招商银行",
    sourceExternalId: null,
    sourceFileHash: null,
    importedAt: "2026-06-21T00:00:00Z",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-20T17:00:00Z",
  },
]

// ── Statement lines ─────────────────────────────────────────────────────────
// The page only reads `.length` ("导入证据 N 行"). One line per imported event.
const statementLines = cashflowEvents.map((event) => ({
  id: event.statementLineId,
  source: event.source,
  postedAt: event.date,
  amount: event.amount,
  currency: event.currency,
  description: event.description,
  status: "matched",
}))

export const importsData: Record<string, unknown> = {
  "cashflow.list": cashflowEvents,
  "imports.statementLines": statementLines,
  "reference.categories": categories,
}
