/**
 * @purpose Register static mock data for the ported Overview page's tRPC queries.
 * @role    Side-effect module: importing it populates the mock tRPC registry so the
 *          verbatim-copied OverviewPage renders realistic Chinese finance numbers.
 * @deps    @mock/lib/trpc registry. Dates are anchored near 2026-06-21.
 * @gotcha  assets.snapshots is consumed twice (latest + history) off ONE registered dataset:
 *          liquid (cash/bank/wallet) items carry a single current snapshot so the liquid sum
 *          stays clean, while growth lives on investment/real-estate items so the 12-month
 *          net-worth trend still rises without inflating liquid assets.
 */

// ── Cashflow ──────────────────────────────────────────────────────────────
// June 2026 events (this-month range). Mix of expenses + income.
const cashflowEvents = [
  {
    id: "cf-1",
    eventDate: "2026-06-02",
    date: "2026-06-02",
    title: "盒马鲜生",
    counterparty: "盒马鲜生",
    description: "生鲜采购",
    amount: "286.40",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "餐饮",
    sourceKind: "import",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "cf-2",
    eventDate: "2026-06-04",
    date: "2026-06-04",
    title: "滴滴出行",
    counterparty: "滴滴出行",
    description: "通勤打车",
    amount: "62.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "交通",
    sourceKind: "import",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-04T09:00:00Z",
  },
  {
    id: "cf-3",
    eventDate: "2026-06-06",
    date: "2026-06-06",
    title: "京东商城",
    counterparty: "京东商城",
    description: "日用百货",
    amount: "458.90",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "购物",
    sourceKind: "import",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-06T20:00:00Z",
  },
  {
    id: "cf-4",
    eventDate: "2026-06-08",
    date: "2026-06-08",
    title: "海底捞",
    counterparty: "海底捞",
    description: "朋友聚餐",
    amount: "512.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "餐饮",
    sourceKind: "import",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-08T19:30:00Z",
  },
  {
    id: "cf-5",
    eventDate: "2026-06-10",
    date: "2026-06-10",
    title: "工资",
    counterparty: "公司发薪",
    description: "六月工资",
    amount: "32000.00",
    currency: "CNY",
    direction: "in",
    flowKind: "income",
    categoryName: "收入",
    sourceKind: "import",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "cf-6",
    eventDate: "2026-06-11",
    date: "2026-06-11",
    title: "星巴克",
    counterparty: "星巴克",
    description: "咖啡",
    amount: "39.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "餐饮",
    sourceKind: "import",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-11T08:30:00Z",
  },
  {
    id: "cf-7",
    eventDate: "2026-06-13",
    date: "2026-06-13",
    title: "优衣库",
    counterparty: "优衣库",
    description: "夏装",
    amount: "699.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "购物",
    sourceKind: "import",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-13T15:00:00Z",
  },
  {
    id: "cf-8",
    eventDate: "2026-06-15",
    date: "2026-06-15",
    title: "万达影城",
    counterparty: "万达影城",
    description: "电影票",
    amount: "98.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "娱乐",
    sourceKind: "import",
    source: "支付宝",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-15T20:00:00Z",
  },
  {
    id: "cf-9",
    eventDate: "2026-06-17",
    date: "2026-06-17",
    title: "美团外卖",
    counterparty: "美团外卖",
    description: "工作日午餐",
    amount: "44.50",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "餐饮",
    sourceKind: "import",
    source: "微信",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-17T12:00:00Z",
  },
  {
    id: "cf-10",
    eventDate: "2026-06-18",
    date: "2026-06-18",
    title: "中国移动",
    counterparty: "中国移动",
    description: "话费充值",
    amount: "100.00",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "通讯",
    sourceKind: "import",
    source: "中国移动",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-18T11:00:00Z",
  },
  {
    id: "cf-11",
    eventDate: "2026-06-19",
    date: "2026-06-19",
    title: "理财收益",
    counterparty: "招商银行",
    description: "货币基金收益",
    amount: "186.20",
    currency: "CNY",
    direction: "in",
    flowKind: "income",
    categoryName: "收入",
    sourceKind: "import",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-19T00:00:00Z",
  },
  {
    id: "cf-12",
    eventDate: "2026-06-20",
    date: "2026-06-20",
    title: "永辉超市",
    counterparty: "永辉超市",
    description: "周末采购",
    amount: "312.80",
    currency: "CNY",
    direction: "out",
    flowKind: "expense",
    categoryName: "餐饮",
    sourceKind: "import",
    source: "招商银行",
    includeInAnalytics: true,
    status: "active",
    classificationSource: "rule",
    tags: [],
    createdAt: "2026-06-20T17:00:00Z",
  },
]

// ── Assets ────────────────────────────────────────────────────────────────
// Liquid items: ONE current snapshot each (clean liquid sum).
// Growth items: monthly snapshots across the last 12 months (rising trend).
function monthKey(monthsAgo: number): string {
  const d = new Date("2026-06-15T00:00:00Z")
  d.setMonth(d.getMonth() - monthsAgo)
  return d.toISOString().slice(0, 10)
}

const liquidSnapshots = [
  {
    id: "as-cash",
    assetItemId: "ai-cash",
    accountName: "现金钱包",
    assetType: "cash",
    snapshotAt: "2026-06-15",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "8500",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  {
    id: "as-cmb",
    assetItemId: "ai-cmb",
    accountName: "招商银行储蓄",
    assetType: "bank",
    snapshotAt: "2026-06-15",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "186000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
  {
    id: "as-alipay",
    assetItemId: "ai-alipay",
    accountName: "支付宝余额宝",
    assetType: "wallet",
    snapshotAt: "2026-06-15",
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: "42000",
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  },
]

// Investment + real estate snapshots over 12 months, plus a liability.
const growthSnapshots: Array<Record<string, unknown>> = []
for (let m = 11; m >= 0; m -= 1) {
  const at = monthKey(m)
  const grown = (m: number) => 1 - m * 0.012 // older months slightly lower
  growthSnapshots.push({
    id: `as-fund-${m}`,
    assetItemId: "ai-fund",
    accountName: "天弘基金组合",
    assetType: "investment",
    snapshotAt: at,
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: Math.round(620000 * grown(m)).toString(),
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  })
  growthSnapshots.push({
    id: `as-house-${m}`,
    assetItemId: "ai-house",
    accountName: "自住房产估值",
    assetType: "real_estate",
    snapshotAt: at,
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    valueNumber: Math.round(2050000 * grown(m * 0.4)).toString(),
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  })
  growthSnapshots.push({
    id: `as-loan-${m}`,
    assetItemId: "ai-loan",
    accountName: "房贷余额",
    assetType: "liability",
    snapshotAt: at,
    quantityNumber: null,
    quantityCurrency: null,
    quantityAmount: null,
    quantityUnit: null,
    // Liability shrinks over time (older months owed more).
    valueNumber: Math.round(560000 + m * 4200).toString(),
    valueCurrency: "CNY",
    source: "manual",
    note: null,
    meta: null,
  })
}

const assetsSnapshots = [...liquidSnapshots, ...growthSnapshots]

// Net worth totals (display/base = CNY).
const assetsNetWorth = {
  netWorth: { number: "2598500", currency: "CNY" },
  assetValue: { number: "3158500", currency: "CNY" },
  liabilityValue: { number: "560000", currency: "CNY" },
  missingFx: [],
}

// ── Subscriptions ─────────────────────────────────────────────────────────
const subscriptionsList = [
  {
    id: "sub-1",
    name: "网易云音乐",
    merchant: "网易",
    amount: "15",
    currency: "CNY",
    billingCycle: "monthly",
    intervalCount: 1,
    nextChargeDate: "2026-06-25",
    autoRenew: true,
    categoryId: null,
    status: "active",
    note: null,
  },
  {
    id: "sub-2",
    name: "iCloud 存储",
    merchant: "Apple",
    amount: "21",
    currency: "CNY",
    billingCycle: "monthly",
    intervalCount: 1,
    nextChargeDate: "2026-06-28",
    autoRenew: true,
    categoryId: null,
    status: "active",
    note: null,
  },
  {
    id: "sub-3",
    name: "爱奇艺会员",
    merchant: "爱奇艺",
    amount: "25",
    currency: "CNY",
    billingCycle: "monthly",
    intervalCount: 1,
    nextChargeDate: "2026-07-05",
    autoRenew: true,
    categoryId: null,
    status: "active",
    note: null,
  },
]

const subscriptionsOccurrences = [
  {
    id: "subocc-1",
    subscriptionId: "sub-1",
    dueDate: "2026-06-25",
    amount: "15",
    currency: "CNY",
    status: "scheduled",
  },
  {
    id: "subocc-2",
    subscriptionId: "sub-2",
    dueDate: "2026-06-28",
    amount: "21",
    currency: "CNY",
    status: "scheduled",
  },
  {
    id: "subocc-3",
    subscriptionId: "sub-3",
    dueDate: "2026-07-05",
    amount: "25",
    currency: "CNY",
    status: "scheduled",
  },
]

// ── Loans ─────────────────────────────────────────────────────────────────
const loansList = [
  {
    id: "loan-1",
    name: "招商银行房贷",
    lender: "招商银行",
    currency: "CNY",
    principalAmount: "800000",
    currentPrincipalEstimate: "560000",
    annualRateBps: 415,
    repaymentMethod: "equal_installment",
    paymentAmount: "4280",
    paymentDay: 22,
    startDate: "2020-07-22",
    termMonths: 360,
    status: "active",
    note: null,
  },
]

const loansOccurrences = [
  {
    id: "loanocc-1",
    loanId: "loan-1",
    dueDate: "2026-06-22",
    paymentAmount: "4280",
    principalAmount: "2350",
    interestAmount: "1930",
    feeAmount: "0",
    remainingPrincipalEstimate: "557650",
    status: "scheduled",
  },
]

const loansFuturePressure = {
  subscriptions: "61",
  loans: "4280",
  total: "4341",
  currency: "CNY",
}

// ── Budgets ───────────────────────────────────────────────────────────────
const budgetsPeriods = [
  {
    id: "bp-1",
    budgetSetId: "bs-1",
    periodKind: "month",
    periodStart: "2026-06-01",
    periodEnd: "2026-06-30",
    currency: "CNY",
    status: "active",
  },
]

const budgetsProgress = [
  {
    budgetItemId: "bi-1",
    budgetName: "餐饮",
    budgeted: "2500",
    referenceUsed: "1194.70",
    remaining: "1305.30",
    currency: "CNY",
    color: "var(--c-food)",
    categoryIds: [],
  },
  {
    budgetItemId: "bi-2",
    budgetName: "购物",
    budgeted: "2000",
    referenceUsed: "1157.90",
    remaining: "842.10",
    currency: "CNY",
    color: "var(--c-shop)",
    categoryIds: [],
  },
  {
    budgetItemId: "bi-3",
    budgetName: "交通",
    budgeted: "600",
    referenceUsed: "62.00",
    remaining: "538.00",
    currency: "CNY",
    color: "var(--c-trans)",
    categoryIds: [],
  },
  {
    budgetItemId: "bi-4",
    budgetName: "娱乐",
    budgeted: "500",
    referenceUsed: "98.00",
    remaining: "402.00",
    currency: "CNY",
    color: "var(--c-fun)",
    categoryIds: [],
  },
  {
    budgetItemId: "bi-5",
    budgetName: "通讯",
    budgeted: "150",
    referenceUsed: "100.00",
    remaining: "50.00",
    currency: "CNY",
    color: "var(--c-other)",
    categoryIds: [],
  },
]

// ── Reference / FX ────────────────────────────────────────────────────────
const referenceCurrentRates = {
  base: "CNY",
  asOf: "2026-06-21",
  rates: {
    USD: "7.18",
    EUR: "7.82",
    HKD: "0.92",
    JPY: "0.046",
  },
}

export const overviewData: Record<string, unknown> = {
  "cashflow.list": cashflowEvents,
  "assets.snapshots": assetsSnapshots,
  "assets.netWorth": assetsNetWorth,
  "subscriptions.list": subscriptionsList,
  "subscriptions.occurrences": subscriptionsOccurrences,
  "loans.list": loansList,
  "loans.occurrences": loansOccurrences,
  "loans.futurePressure": loansFuturePressure,
  "budgets.periods": budgetsPeriods,
  "budgets.progress": budgetsProgress,
  "reference.currentRates": referenceCurrentRates,
}
